name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Collect versions
        run: |
          echo "nodejs_version=$(cat .tool-versions | grep '^node ' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
          echo "pnpm_version=$(cat .tool-versions | grep 'pnpm' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm_version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodejs_version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Check formatting
        run: pnpm stylecheck
      - name: Test
        run: pnpm test
      - name: Test package exports
        run: pnpm test:package
